import { useEffect, useMemo, useState } from 'react';
import { CloudRain, Droplets, ExternalLink, RefreshCw, Shirt, ThermometerSun, Waves, Wind } from 'lucide-react';

type Point={date:string,value:number}; type Forecast={date:string,tMax:number,tMin:number,precip:number,wind:number,code:number};
type Data={updatedAt:string;flow:number;flowTime:string;flowChange24h:number|null;waterTemp:number;waterTime:string;airTemp:number;apparentTemp:number;precip:number;weatherCode:number;forecast:Forecast[];flowMonth:Point[];flowYear:Point[];tempMonth:Point[];tempYear:Point[];webcamUrl:string};
const fmt=(n:number,d=1)=>new Intl.NumberFormat('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d}).format(n);
const day=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('de-DE',{weekday:'short'});
function icon(code:number){if(code===0)return'☀';if(code<=3)return'⛅';if(code<=67)return'🌧';return'☁'}
function outfit(w:number,a:number){if(w>=20&&a>=20)return'Neoprenshirt kurzarm';if(w>=18&&a>=15)return'Neoprenshirt langarm';if(w>=16&&a>=12)return'Neoprenshirt langarm · Paddeljacke optional';if(w>=14&&a>=10)return'Neoprenshirt kurzarm · Paddeljacke';if(w>=12)return'Long John · Neoprenshirt kurzarm · Paddeljacke';return'Long John · Neoprenshirt langarm · Paddeljacke'}
function status(flow:number){if(flow>=50)return{label:'Gute Chance auf Wasser',tone:'good',text:'Der Abfluss am Pegel Haunstetten liegt bei mindestens 50 m³/s. Trotzdem Streckenfreigabe vor Ort prüfen.'};if(flow>=40)return{label:'Grenzbereich',tone:'warn',text:'Der Abfluss liegt unter dem langjährigen 50-m³/s-Richtwert. Wasserführung am Eiskanal kann eingeschränkt sein.'};return{label:'Eher zu wenig Wasser',tone:'bad',text:'Unter 50 m³/s bleibt die Wettkampfstrecke nach Betreiberinformation in der Regel ohne ausreichende Wasserführung.'}}
function Chart({points,unit,threshold}:{points:Point[];unit:string;threshold?:number}){const p=points.slice(-60);if(!p.length)return <div className="empty">Messdaten werden geladen …</div>;const vals=p.map(x=>x.value),min=Math.min(...vals,threshold??Infinity),max=Math.max(...vals,threshold??-Infinity),span=Math.max(1,max-min);const coords=p.map((x,i)=>`${(i/(p.length-1||1))*100},${92-((x.value-min)/span)*76}`).join(' ');const ty=threshold==null?null:92-((threshold-min)/span)*76;return <div className="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none">{ty!=null&&<line x1="0" x2="100" y1={ty} y2={ty} className="threshold"/>}<polyline points={coords} className="line"/></svg><div className="chartMeta"><span>{fmt(min,unit==='°C'?1:0)} {unit}</span><span>{fmt(max,unit==='°C'?1:0)} {unit}</span></div></div>}
export default function App(){const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[err,setErr]=useState('');const[range,setRange]=useState<'month'|'year'>('month');async function load(){setLoading(true);setErr('');try{const r=await fetch('/api/dashboard');if(!r.ok)throw new Error();setData(await r.json())}catch{setErr('Live-Daten konnten nicht geladen werden.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);const paddle=useMemo(()=>data?status(data.flow):null,[data]);return <main className="page">
<header className="top"><div><div className="kicker">EISKANAL AUGSBURG · LIVE DASHBOARD</div><h1>Eiskanal Augsburg</h1><p className="updated">Zuletzt aktualisiert: {data?new Date(data.updatedAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}):'—'}</p></div><button onClick={()=>void load()} disabled={loading}><RefreshCw size={17} className={loading?'spin':''}/>{loading?'Aktualisiere…':'Aktualisieren'}</button></header>{err&&<div className="error">{err}</div>}
<section className={`paddle ${paddle?.tone||''}`}><div><span>PADDELCHECK</span><strong>{paddle?.label||'Bedingungen werden geladen'}</strong><p>{paddle?.text||'Die aktuellen Messwerte des LfU Bayern werden abgerufen.'}</p></div><Waves size={42}/></section>
<section className="grid3"><article className="metric"><Waves/><span>ABFLUSS · HAUNSTETTEN</span><em>LIVE</em><b>{data?fmt(data.flow):'—'} <small>m³/s</small></b><p>{data?.flowChange24h==null?'24 h: —':`24 h: ${data.flowChange24h>=0?'+':''}${fmt(data.flowChange24h)} m³/s`}</p><small>{data?.flowTime||'LfU-Messdaten werden geladen'}</small></article><article className="metric"><Droplets/><span>WASSERTEMPERATUR · HOCHABLASS</span><em>LIVE</em><b>{data?fmt(data.waterTemp):'—'} <small>°C</small></b><p>Lech am Hochablass</p><small>{data?.waterTime||'LfU-Messdaten werden geladen'}</small></article><article className="metric"><ThermometerSun/><span>WETTER JETZT</span><em>LIVE</em><b>{data?Math.round(data.airTemp):'—'} <small>°C</small></b><p>{data?`${fmt(data.precip)} mm · gefühlt ${Math.round(data.apparentTemp)} °C`:'Open-Meteo wird geladen'}</p><small>Augsburg · Eiskanal</small></article></section>
<section className="outfit"><div><Shirt/><span>BEKLEIDUNGSEMPFEHLUNG</span><em>LIVE</em></div><strong>{data?outfit(data.waterTemp,data.airTemp):'Wird geladen'}</strong><p>Empfehlung folgt aus Luft- und Wassertemperatur. Helm, Schwimmweste, Spritzdecke und Neoprenschuhe immer dabei.</p></section>
<section className="chartsHead"><div><span>VERLAUF</span><h2>Messdaten</h2></div><div className="seg"><button className={range==='month'?'active':''} onClick={()=>setRange('month')}>1 Monat</button><button className={range==='year'?'active':''} onClick={()=>setRange('year')}>12 Monate</button></div></section><section className="grid2"><article className="panel"><h3>Abfluss</h3><Chart points={data?(range==='month'?data.flowMonth:data.flowYear):[]} unit="m³/s" threshold={50}/></article><article className="panel"><h3>Wassertemperatur</h3><Chart points={data?(range==='month'?data.tempMonth:data.tempYear):[]} unit="°C"/></article></section>
<section className="grid2 lower"><article className="panel webcam"><div className="panelTitle"><div><span>AKTUELLES BILD</span><h3>Webcam Olympiastrecke</h3></div><small>Update alle 2 Stunden</small></div>{data?.webcamUrl?<img src={data.webcamUrl} alt="Aktuelles Webcam-Bild der Olympiastrecke am Augsburger Eiskanal"/>:<div className="webcamPlaceholder">Webcam wird geladen</div>}<a href="https://www.eiskanal-augsburg.de/" target="_blank" rel="noreferrer">Webcam in der Originalansicht öffnen <ExternalLink size={14}/></a><p>Aus Datenschutzgründen aktualisiert der Betreiber das Bild alle zwei Stunden.</p></article><article className="panel forecast"><div className="panelTitle"><div><span>AUGSBURG · 7 TAGE</span><h3>Wetterausblick</h3></div><CloudRain/></div><div className="days">{data?.forecast.map((f,i)=><div className="day" key={f.date}><b>{i===0?'Heute':day(f.date)}</b><i>{icon(f.code)}</i><span>{Math.round(f.tMax)} °</span><span>{Math.round(f.tMin)} °</span><small>{fmt(f.precip)} mm</small><small><Wind size={12}/>{Math.round(f.wind)} km/h</small></div>)}</div><p>Tageswerte · Niederschlag und maximale Windgeschwindigkeit · Open-Meteo</p></article></section>
<footer>Messdaten: Bayerisches Landesamt für Umwelt / HND Bayern · Wetter: Open-Meteo<br/>Die Einschätzung ersetzt keine Prüfung der Streckenfreigabe vor Ort.</footer></main>}
