import type { VercelRequest,VercelResponse } from '@vercel/node';
import { neon } from '@neondatabase/serverless';
const FLOW_LIVE='https://www.hnd.bayern.de/pegel/iller_lech/haunstetten-12003500/abfluss';
const FLOW_YEAR='https://www.gkd.bayern.de/de/fluesse/abfluss/bayern/haunstetten-12003500/jahreswerte';
const TEMP_LIVE='https://www.nid.bayern.de/wassertemperatur/bayern/augsburg-hochablass-12004002';
const TEMP_YEAR='https://www.gkd.bayern.de/de/fluesse/wassertemperatur/bayern/augsburg-hochablass-12004002/jahreswerte';
const WEATHER='https://api.open-meteo.com/v1/forecast?latitude=48.34645&longitude=10.93594&current=temperature_2m,apparent_temperature,precipitation,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max&wind_speed_unit=kmh&timezone=Europe%2FBerlin&forecast_days=7';
const WEBCAM='https://www.eiskanal-augsburg.de/webcam/webcam.jpg';
function clean(s:string){return s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/\s+/g,' ')}
function deNum(s:string){return Number(s.replace('.','').replace(',','.'))}
function parseLiveFlow(html:string){const t=clean(html);const m=t.match(/Letzter Messwert vom\s*(\d{2}\.\d{2}\.\d{2,4})\s*(\d{2}:\d{2})\s*Uhr:\s*([\d,.]+)\s*m³\/s/i)||t.match(/(\d{2}\.\d{2}\.\d{4})\s+(\d{2}:\d{2})\s+([\d,.]+)\s*m³\/s/i);if(!m)throw new Error('flow');return{value:deNum(m[3]),time:`${m[1]} ${m[2]}`}}
function parseLiveTemp(html:string){const t=clean(html);const rows=[...t.matchAll(/(\d{2}\.\d{2}\.\d{4})\s+(\d{2}:\d{2})(?:\s*Uhr)?\s+([0-9]{1,2}[\.,][0-9])/g)];if(!rows.length)throw new Error('temp');return{value:deNum(rows[0][3]),time:`${rows[0][1]} ${rows[0][2]}`}}
function parseDaily(html:string){const t=clean(html),out:{date:string,value:number}[]=[];const re=/(\d{2}\.\d{2}\.\d{4})\s+([\d,.]+)\s+([\d,.]+)\s+([\d,.]+)/g;let m;while((m=re.exec(t))){const[d,mo,y]=m[1].split('.');const v=deNum(m[2]);if(Number.isFinite(v))out.push({date:`${y}-${mo}-${d}`,value:v})}const seen=new Map<string,number>();out.forEach(x=>seen.set(x.date,x.value));return[...seen].map(([date,value])=>({date,value})).sort((a,b)=>a.date.localeCompare(b.date))}
function weekly(points:{date:string,value:number}[]){const out:{date:string,value:number}[]=[];for(let i=0;i<points.length;i+=7){const c=points.slice(i,i+7);if(c.length)out.push({date:c[Math.floor(c.length/2)].date,value:c.reduce((s,x)=>s+x.value,0)/c.length})}return out}
export default async function handler(req:VercelRequest,res:VercelResponse){if(req.method!=='GET')return res.status(405).end();try{const y=new Date().getFullYear(),prev=y-1;const[flowH,tempH,flowY,tempY,flowP,tempP,w]=await Promise.all([fetch(FLOW_LIVE).then(r=>r.text()),fetch(TEMP_LIVE).then(r=>r.text()),fetch(`${FLOW_YEAR}?beginn=01.01.${y}&ende=31.12.${y}`).then(r=>r.text()),fetch(`${TEMP_YEAR}?beginn=01.01.${y}&ende=31.12.${y}`).then(r=>r.text()),fetch(`${FLOW_YEAR}?beginn=01.01.${prev}&ende=31.12.${prev}`).then(r=>r.text()),fetch(`${TEMP_YEAR}?beginn=01.01.${prev}&ende=31.12.${prev}`).then(r=>r.text()),fetch(WEATHER).then(r=>r.json())]);const flow=parseLiveFlow(flowH),temp=parseLiveTemp(tempH);const fd=[...parseDaily(flowP),...parseDaily(flowY)],td=[...parseDaily(tempP),...parseDaily(tempY)];const cutoff=new Date();cutoff.setDate(cutoff.getDate()-365);const cut=cutoff.toISOString().slice(0,10),f365=fd.filter(x=>x.date>=cut),t365=td.filter(x=>x.date>=cut),f30=f365.slice(-30),t30=t365.slice(-30);const change=f30.length>1?flow.value-f30[Math.max(0,f30.length-2)].value:null;const d=w.daily;const forecast=d.time.map((date:string,i:number)=>({date,tMax:d.temperature_2m_max[i],tMin:d.temperature_2m_min[i],precip:d.precipitation_sum[i],wind:d.wind_speed_10m_max[i],code:d.weather_code[i]}));const body={updatedAt:new Date().toISOString(),flow:flow.value,flowTime:flow.time,flowChange24h:change,waterTemp:temp.value,waterTime:temp.time,airTemp:w.current.temperature_2m,apparentTemp:w.current.apparent_temperature,precip:w.current.precipitation,weatherCode:w.current.weather_code,forecast,flowMonth:f30,flowYear:weekly(f365),tempMonth:t30,tempYear:weekly(t365),webcamUrl:WEBCAM};if(process.env.DATABASE_URL){const sql=neon(process.env.DATABASE_URL);await sql`INSERT INTO dashboard_snapshots (flow,water_temp,air_temp,payload) VALUES (${body.flow},${body.waterTemp},${body.airTemp},${JSON.stringify(body)}::jsonb)`}return res.status(200).json(body)}catch(e){console.error(e);if(process.env.DATABASE_URL){try{const sql=neon(process.env.DATABASE_URL);const rows=await sql`SELECT payload FROM dashboard_snapshots ORDER BY captured_at DESC LIMIT 1`;if(rows.length)return res.status(200).json(rows[0].payload)}catch{}}return res.status(502).json({error:'dashboard_fetch_failed'})}}